### ISSUE TITLE
Error: Cannot find module '../index.js' in 1.1.0

### ISSUE THREAD

**Issue by supermario** [wolfadex/elm-license-finder#3]
It appears there's a regression in 1.1.0 caused by this line:

https://github.com/wolfadex/elm-license-finder/commit/57a1da64dde8f5f04a24f29585bab20e3ccbcaac#diff-919840ecece432f184371d66ac4f5579R4

resulting in:

```
$ npm install -g elm-license-finder
/usr/local/bin/elm-license-finder -> /usr/local/lib/node_modules/elm-license-finder/elm-license-finder.js
+ elm-license-finder@1.1.0
updated 1 package in 0.265s

$ elm-license-finder
internal/modules/cjs/loader.js:964
    throw err;
    ^

Error: Cannot find module '../index.js'
Require stack:
- /usr/local/lib/node_modules/elm-license-finder/elm-license-finder.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:961:17)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/elm-license-finder/elm-license-finder.js:4:26)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/elm-license-finder/elm-license-finder.js'
  ]
}
```

**Comment by wolfadex** [comment]
That was a silly thing to do on my part. Sorry about that. It's fixed now in 1.1.1
